apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: neyro
resources:
  - namespace.yaml
  - application.yaml
  - storage.yaml
  - network.yaml
configMapGenerator:
  - name: neyro-config
    literals:
      - APP_ENV=production
      - DEV_AUTH=0
      - BILLING_ENABLED=0
      - BUSINESS_MODE_ENABLED=0
      - HOST=0.0.0.0
      - PORT=8080
      - FORWARDED_ALLOW_IPS=127.0.0.1
      - PUBLIC_URL=https://flipbazar.ru
